# Generated by Django 6.0 on 2026-02-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='courses.student'),
        ),
        migrations.AddField(
            model_name='courses',
            name='categories',
            field=models.ManyToManyField(related_name='courses', to='courses.category'),
        ),
    ]
